server/Main.ts, server/application/Configuration.ts, server/controllers/SlackController.ts
=> Slack commands endpoint

package-lock.json, server/commands/HelpCommand.ts
=> Fixed duplicated entries in Help command

.github/workflows/build.yml, package-lock.json, package.json, packages/admin-panel/package-lock.json, packages/admin-panel/package.json, packages/admin-panel/src/admin-panel.html, packages/devops/package-lock.json, packages/devops/package.json, packages/fm-player/package-lock.json, packages/fm-player/package.json, packages/fm-player/src/fm-player.html, packages/service/package-lock.json, packages/service/package.json, packages/service/src/api/slack/model/slack-response-dto.ts, packages/service/src/api/text/model/text-command-response-dto.ts, packages/service/src/domain/commands/processors/add-command.ts, packages/service/src/domain/commands/processors/skip-command.ts, packages/service/src/domain/commands/processors/speed-command.ts
- Updated Node.js to version 16
- Updated React to version 17
- Updated build process for frontend packages
- Updated ESLint rules
=> Upgrade dependencies

packages/service/src/domain/commands/processors/random-x-command.ts
Add random sound command, for example:
/fm random-x
/fm random-x tag
=> Add random sound command

packages/client/src/fm-player/services/event-stream-client.ts, packages/client/src/fm-player/services/player-state-service.ts, packages/service/src/domain/commands/processors/playback-shuffle-command.ts, packages/service/src/event-stream/model/events.ts, packages/service/src/event-stream/player-event-stream.ts
https://github.com/Deseteral/lebkuchen-fm/issues/166
=> add shuffle command

README.md, packages/client/src/login/components/LoginForm.tsx, packages/client/src/xsound-upload-form/components/XSoundUploadForm.tsx, packages/service/src/api/x-sounds/x-sounds-controller.ts, packages/service/src/domain/x-sounds/x-sounds-service.ts
Now we can add tags just in upload form. Also fixed login bg unresolved path
=> Adding tags in xSoundUploadForm; Login bg fix

packages/service/src/domain/commands/processors/playback-current-command.ts, packages/service/src/domain/player-state/player-state.ts
What:
- change format of the `current` command message
- add timestamp of currently playing song
Why:
- discord added support for list markdown and this broke our formatting
- discord added support for link masking 
- disable default youtube url preview (by surrounding url with <>)
=> change format of the current command message

README.md, packages/client/src/fm-player/components/FmPlayer.tsx, packages/client/src/fm-player/components/UsersButton.tsx, packages/client/src/fm-player/icons/UsersIcon.tsx, packages/client/src/fm-player/services/connected-users-service.ts, packages/client/src/fm-player/services/event-stream-client.ts, packages/service/src/event-stream/model/events.ts, packages/service/src/event-stream/player-event-stream.ts
Added Users counter in Player view:
=> User updates

packages/client/src/fm-player/components/UsersButton.tsx
=> Current users list directly in a player

packages/client/src/sound-board/components/SoundBoard.tsx
- prioritise exact match
- prioritise sounds more frequently played
solves https://github.com/Deseteral/lebkuchen-fm/issues/221
=> sort sounds when searching

.gitignore, .vscode/settings.json, packages/client/src/fm-player/services/event-stream-client.ts, packages/client/src/fm-player/services/speech-service.ts, packages/client/src/fm-player/services/youtube-player-service.ts, packages/client/src/services/tween.ts, packages/service/package.json, packages/service/src/domain/commands/processors/say-command.ts, packages/service/src/domain/radio-personality/radio-personality-service.ts, packages/service/src/event-stream/player-event-stream.ts, packages/service/src/infrastructure/configuration.ts, packages/service/src/infrastructure/llm-generator.ts, yarn.lock
=> Radio personality

packages/service/src/domain/commands/processors/call-command.ts, packages/service/src/domain/radio-personality/radio-personality-service.ts
=> Message from listener command

packages/client/package.json, packages/client/src/fm-player/services/youtube-player-service.ts, yarn.lock
See docs:
https://github.com/feross/yt-player?tab=readme-ov-file#optshost-string
=> Privacy settings for YouTube player

service/src/main/kotlin/xyz/lebkuchenfm/api/xsounds/XSoundsEndpoint.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/xsounds/XSoundsRepository.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/xsounds/XSoundsService.kt, service/src/main/kotlin/xyz/lebkuchenfm/external/storage/repos/XSoundsMongoRepository.kt
- add filter by tag
- beta features parity
=> [beta-backend] add x-sounds filter by tag

service/build.gradle.kts, service/gradle.properties, service/src/main/kotlin/xyz/lebkuchenfm/Application.kt, service/src/main/kotlin/xyz/lebkuchenfm/external/discord/DiscordClient.kt, service/src/main/resources/application.yaml, service/src/main/resources/logback.xml
- add discord client with `kord` as dependency
=> [beta backend] add discord client

packages/client/src/services/user-account-service.ts, packages/service/package.json, packages/service/src/api/auth/auth-controller.ts, packages/service/src/api/auth/model/auth-request-dto.ts, packages/service/src/lib.ts, yarn.lock
Instead of JSON based login request we can move to form-data based login flow. This will allow us to test the upcoming v3 version of backend service with current client.
=> Forward compatibility of login form

service/src/main/kotlin/xyz/lebkuchenfm/Application.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/commands/CommandProcessorRegistry.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/commands/processors/HelpCommandProcessor.kt, service/src/main/kotlin/xyz/lebkuchenfm/external/discord/DiscordClient.kt
Test:
```
curl -X POST localhost:8080/api/commands/text \
-H "Content-Type: application/json" \
-d '{"text": "/fmbeta help x"}' | 
jq -r '.textResponse'
```
=> [beta backend] add help command

packages/client-beta/package.json, packages/client-beta/src/apps/Player/services/player-state-service.ts, packages/client-beta/src/apps/Player/services/youtube-player-service.tsx, packages/client-beta/src/types/event-data.ts, packages/client-beta/src/types/local-events.ts
PlayerState can have null value when Player is not subscribed for WebSocket player events
=> PlayerState can have `null` value 

service/src/main/kotlin/xyz/lebkuchenfm/Application.kt, service/src/main/kotlin/xyz/lebkuchenfm/api/eventstream/models/EventDto.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/commands/processors/PlaybackPauseCommandProcessor.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/commands/processors/PlaybackResumeCommandProcessor.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/commands/processors/PlaybackSkipCommandProcessor.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/eventstream/Event.kt
=> [beta backend] add playback commands processors

packages/client-beta/src/services/socket-connection-client.ts
The issue was that when closing a WebSocket connection, we didn’t remove its event listeners. As a result, the `WebSocket` instance wasn’t subject to garbage collection and kept reconnecting to the backend, exponentially multiplying the number of connections in a single client.
The fix involves removing the event listeners when disconnecting the WebSocket.
=> Fix a bug with duplicating event listeners on WS reconnect

client/package.json, docs/auth.md, scripts/fm, service/gradle.properties, service/src/main/kotlin/xyz/lebkuchenfm/api/commands/CommandsEndpoint.kt
=> Fix commands endpoint not handling Content-Type correctly

.github/workflows/version-check.yml, client/package.json, service/gradle.properties, service/src/main/kotlin/xyz/lebkuchenfm/external/storage/mongo/repositories/SessionsMongoRepository.kt, service/src/main/kotlin/xyz/lebkuchenfm/external/storage/mongo/repositories/SongsMongoRepository.kt, service/src/main/kotlin/xyz/lebkuchenfm/external/storage/mongo/repositories/UsersMongoRepository.kt, service/src/main/kotlin/xyz/lebkuchenfm/external/storage/mongo/repositories/XSoundsMongoRepository.kt
=> Make MongoDB entity declarations consistent

service/src/main/kotlin/xyz/lebkuchenfm/Application.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/commands/processors/CallCommandProcessor.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/radiopersonality/RadioPersonalityBrain.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/radiopersonality/RadioPersonalityBrainProvider.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/radiopersonality/RadioPersonalityService.kt, service/src/main/kotlin/xyz/lebkuchenfm/domain/radiopersonality/llmprompts/LlmPrompts.kt, service/src/main/kotlin/xyz/lebkuchenfm/external/gemini/GeminiRadioPersonality.kt, service/src/main/kotlin/xyz/lebkuchenfm/external/storage/mongo/repositories/LlmPersonalityPromptsMongoRepository.kt, service/src/main/kotlin/xyz/lebkuchenfm/external/storage/mongo/repositories/LlmSituationPromptsMongoRepository.kt
=> Call command

client/package.json, service/gradle.properties, service/src/main/kotlin/xyz/lebkuchenfm/external/storage/dropbox/DropboxClient.kt
- escape non ascii characters in `Dropbox-API-Arg`
- https://www.dropbox.com/developers/reference/json-encoding 
-----
Closes https://github.com/Deseteral/lebkuchen-fm/issues/325
=> [Bugfix] dropbox request encoding

client/package.json, service/gradle.properties, service/src/main/kotlin/xyz/lebkuchenfm/external/discord/DiscordClient.kt
fixes https://github.com/Deseteral/lebkuchen-fm/issues/351
=> fix discord prompt comparison

client/.eslintrc, client/package.json, client/src/_playground/Buttons.playground.tsx, client/src/_playground/index.html, client/src/_playground/index.playground.tsx, client/src/_playground/styles.playground.module.css, client/src/apps/DebugSoundUploadForm/DebugSoundUploadForm.tsx, client/src/apps/Users/Users.tsx, client/src/components/Button/Button.module.css, client/src/components/Button/Button.tsx, client/src/components/MenuBar/components/DateWidget/DateWidget.tsx, client/src/components/MenuBar/components/TimeWidget/TimeWidget.tsx, client/src/views/Login/Login.tsx, client/tsconfig.json, client/vite.config.playground.ts, client/vite.config.ts, client/yarn.lock, service/gradle.properties
In `/client` directory you can run `yarn run playground` for new vite dev server only for testing component purposes.
Closes #370 #371
=> Simple playground for testing components. Button component updated.

client/package.json, service/gradle.properties, service/src/main/kotlin/xyz/lebkuchenfm/external/storage/dropbox/DropboxClient.kt
attempt to fix dropbox auth bug
also add more logs for further investigation
=> Bugfix | dropbox auth
